travis:
  secure:
    BINSTAR_TOKEN: lGtbN93CjCF/J8qTD+ad7NKLwqG/i6/Pt4xqAyurAPviw5rceuOtPcmIQdLS7Al7U3nMZyzzgY+H2umOSpxSzLBzOOL/4IvgDj0zQXjDv8KoRtsvXw1YcnQz+5mT7NduVLTAaNBSU+eU7Bx3a7FEDOypHXJad+LrTBJhx8A483XXjwDlDmHgaCLMSgUnohrzVC3Cc461M9BXTHSvWRBhFenv+IVFXrDG7VLx59KkkDiqKXZPOkF0iaftiEPq3/kSLQRWQK5UK8nmDMjfcZEi3D9lk/4reHdCbCSptbw8bYG2Meam2Izy1DIBlXHo4snqoA4DqkLPjgrjC2b0lFm/N/BgEZ018KHyCgQx8aqjut8JckUeonjn97pu4eFkt6HLh7WZsEmqTQ2Pa6Zq1zebZJLvWL/rye23hL1/bx+Z+jHrEITfXErYaXy5AZ4y4zmrH7EX1D3k0tKwyQyrlMLOn7JvNHuoobAKYs7u3GWQRVj915uc5M6d+kooZ3D0g2b9txKsqomyxIyorDOVrGpoB6hNBWaegnQhYv4ZVLOfs+712bLHIg0B8Z/2Uvsi/G9bIA7k7yuAesefryz+vfuY1gVm6q171aSsPV6j17sE0c7S789jTDWNaYyFEw/jxvKjx4yJWznTLRb1QMkm+7P+MPE5W8QQxeIHld/pwmn3gWs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
